use godot::{
    classes::{
        AspectRatioContainer, BoxContainer, Button, CenterContainer, CheckBox, CheckButton,
        CodeEdit, ColorPicker, ColorPickerButton, ColorRect, Container, Control, EditorProperty,
        FlowContainer, GridContainer, HBoxContainer, HFlowContainer, HScrollBar, HSeparator,
        HSlider, HSplitContainer, ItemList, Label, LineEdit, LinkButton, MarginContainer, MenuBar,
        MenuButton, NinePatchRect, OptionButton, Panel, PanelContainer, ProgressBar, ReferenceRect,
        RichTextLabel, ScrollContainer, SpinBox, SplitContainer, SubViewportContainer, TabBar,
        TabContainer, TextEdit, TextureButton, TextureProgressBar, TextureRect, Tree,
        VBoxContainer, VFlowContainer, VScrollBar, VSeparator, VSlider, VSplitContainer,
        VideoStreamPlayer,
    },
    prelude::*,
};
use strum::Display;

#[derive(Debug, Display)]
pub enum GDType {
    AspectRatioContainer,
    BoxContainer,
    Button,
    CenterContainer,
    CheckBox,
    CheckButton,
    CodeEdit,
    ColorPicker,
    ColorPickerButton,
    ColorRect,
    Container,
    Control,
    EditorProperty,
    FlowContainer,
    FoldableContainer,
    GridContainer,
    HBoxContainer,
    HFlowContainer,
    HScrollBar,
    HSeparator,
    HSlider,
    HSplitContainer,
    ItemList,
    Label,
    LineEdit,
    LinkButton,
    MarginContainer,
    MenuBar,
    MenuButton,
    NinePatchRect,
    OptionButton,
    Panel,
    PanelContainer,
    ProgressBar,
    ReferenceRect,
    RichTextLabel,
    ScrollContainer,
    SpinBox,
    SplitContainer,
    SubViewportContainer,
    TabBar,
    TabContainer,
    TextEdit,
    TextureButton,
    TextureProgressBar,
    TextureRect,
    Tree,
    VBoxContainer,
    VFlowContainer,
    VideoStreamPlayer,
    VScrollBar,
    VSeparator,
    VSplitContainer,
    VSlider,
}

impl GDType {
    pub(crate) fn create_instance(&self) -> Gd<Control> {
        match self {
            GDType::AspectRatioContainer => AspectRatioContainer::new_alloc().upcast(),
            GDType::BoxContainer => BoxContainer::new_alloc().upcast(),
            GDType::Button => Button::new_alloc().upcast(),
            GDType::CenterContainer => CenterContainer::new_alloc().upcast(),
            GDType::CheckBox => CheckBox::new_alloc().upcast(),
            GDType::CheckButton => CheckButton::new_alloc().upcast(),
            GDType::CodeEdit => CodeEdit::new_alloc().upcast(),
            GDType::ColorPicker => ColorPicker::new_alloc().upcast(),
            GDType::ColorPickerButton => ColorPickerButton::new_alloc().upcast(),
            GDType::ColorRect => ColorRect::new_alloc().upcast(),
            GDType::Container => Container::new_alloc().upcast(),
            GDType::Control => Control::new_alloc(),
            GDType::EditorProperty => EditorProperty::new_alloc().upcast(),
            GDType::FlowContainer => FlowContainer::new_alloc().upcast(),
            GDType::FoldableContainer => panic!("TODO: FoldableContainer is not instantiable"),
            GDType::GridContainer => GridContainer::new_alloc().upcast(),
            GDType::HBoxContainer => HBoxContainer::new_alloc().upcast(),
            GDType::HFlowContainer => HFlowContainer::new_alloc().upcast(),
            GDType::HScrollBar => HScrollBar::new_alloc().upcast(),
            GDType::HSeparator => HSeparator::new_alloc().upcast(),
            GDType::HSlider => HSlider::new_alloc().upcast(),
            GDType::HSplitContainer => HSplitContainer::new_alloc().upcast(),
            GDType::ItemList => ItemList::new_alloc().upcast(),
            GDType::Label => Label::new_alloc().upcast(),
            GDType::LineEdit => LineEdit::new_alloc().upcast(),
            GDType::LinkButton => LinkButton::new_alloc().upcast(),
            GDType::MarginContainer => MarginContainer::new_alloc().upcast(),
            GDType::MenuBar => MenuBar::new_alloc().upcast(),
            GDType::MenuButton => MenuButton::new_alloc().upcast(),
            GDType::NinePatchRect => NinePatchRect::new_alloc().upcast(),
            GDType::OptionButton => OptionButton::new_alloc().upcast(),
            GDType::Panel => Panel::new_alloc().upcast(),
            GDType::PanelContainer => PanelContainer::new_alloc().upcast(),
            GDType::ProgressBar => ProgressBar::new_alloc().upcast(),
            GDType::ReferenceRect => ReferenceRect::new_alloc().upcast(),
            GDType::RichTextLabel => RichTextLabel::new_alloc().upcast(),
            GDType::ScrollContainer => ScrollContainer::new_alloc().upcast(),
            GDType::SpinBox => SpinBox::new_alloc().upcast(),
            GDType::SplitContainer => SplitContainer::new_alloc().upcast(),
            GDType::SubViewportContainer => SubViewportContainer::new_alloc().upcast(),
            GDType::TabBar => TabBar::new_alloc().upcast(),
            GDType::TabContainer => TabContainer::new_alloc().upcast(),
            GDType::TextEdit => TextEdit::new_alloc().upcast(),
            GDType::TextureButton => TextureButton::new_alloc().upcast(),
            GDType::TextureProgressBar => TextureProgressBar::new_alloc().upcast(),
            GDType::TextureRect => TextureRect::new_alloc().upcast(),
            GDType::Tree => Tree::new_alloc().upcast(),
            GDType::VBoxContainer => VBoxContainer::new_alloc().upcast(),
            GDType::VFlowContainer => VFlowContainer::new_alloc().upcast(),
            GDType::VideoStreamPlayer => VideoStreamPlayer::new_alloc().upcast(),
            GDType::VScrollBar => VScrollBar::new_alloc().upcast(),
            GDType::VSeparator => VSeparator::new_alloc().upcast(),
            GDType::VSlider => VSlider::new_alloc().upcast(),
            GDType::VSplitContainer => VSplitContainer::new_alloc().upcast(),
        }
    }
}
