use godot::{
    classes::{Button, Control, Panel, VBoxContainer},
    prelude::*,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum VNodeKind {
    Control,
    ColorRect,
    GraphEdit,
    ItemList,
    Label,
    LineEdit,
    MenuBar,
    NinePatchRect,
    Panel,
    ReferenceRect,
    RichTextLabel,
    TabBar,
    TextEdit,
    TextureRect,
    Tree,
    VideoStreamPlayer,
    HSeperator,
    VSeparator,
    ProgressBar,
    SpinBox,
    TextureProgressBar,
    HSlider,
    VSlider,
    HScrollBar,
    VScrollbar,
    Button,
    LinkButton,
    TextureButton,
    CheckBox,
    CheckBoxButton,
    ColorPickerButton,
    MenuButton,
    OptionButton,
    Container,
    AspectRatioContainer,
    BoxContainer,
    VBoxContainer,
    HBoxContainer,
    ColorPicker,
    CenterContainer,
    EditorProperty,
    FlowContainer,
    HFlowContainer,
    VFlowContainer,
    GraphElement,
    GraphFrame,
    GraphNode,
    GridContainer,
    MarginContainer,
    PanelContainer,
    ScrollContainer,
    SplitContainer,
    HSplitContainer,
    VSplitContainer,
    SubViewportContainer,
    TabContainer,
}

impl VNodeKind {
    pub fn create_instance(&self) -> Gd<Control> {
        match self {
            VNodeKind::Control => Control::new_alloc(),
            VNodeKind::Button => Button::new_alloc().upcast(),
            VNodeKind::Panel => Panel::new_alloc().upcast(),
            VNodeKind::VBoxContainer => VBoxContainer::new_alloc().upcast(),
            _ => unimplemented!("not supported yet"),
        }
    }
}
