use godot::{
    classes::{
        AspectRatioContainer, BoxContainer, Button, CenterContainer, CheckBox, CheckButton,
        ColorPicker, ColorPickerButton, ColorRect, Container, Control, EditorProperty,
        FlowContainer, GridContainer,
        HBoxContainer, HFlowContainer, HScrollBar, HSeparator, HSlider, HSplitContainer, ItemList,
        Label, LineEdit, LinkButton, MarginContainer, MenuBar, MenuButton, NinePatchRect,
        OptionButton, Panel, PanelContainer, ProgressBar, ReferenceRect, RichTextLabel,
        ScrollContainer, SpinBox, SplitContainer, SubViewportContainer, TabBar, TabContainer,
        TextEdit, TextureButton, TextureProgressBar, TextureRect, Tree, VBoxContainer,
        VFlowContainer, VScrollBar, VSeparator, VSlider, VSplitContainer, VideoStreamPlayer,
    },
    prelude::*,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum VNodeKind {
    Control,
    ColorRect,
    
    ItemList,
    Label,
    LineEdit,
    MenuBar,
    NinePatchRect,
    Panel,
    ReferenceRect,
    RichTextLabel,
    TabBar,
    TextEdit,
    TextureRect,
    Tree,
    VideoStreamPlayer,
    HSeparator,
    VSeparator,
    ProgressBar,
    SpinBox,
    TextureProgressBar,
    HSlider,
    VSlider,
    HScrollBar,
    VScrollbar,
    Button,
    LinkButton,
    TextureButton,
    CheckBox,
    CheckBoxButton,
    ColorPickerButton,
    MenuButton,
    OptionButton,
    Container,
    AspectRatioContainer,
    BoxContainer,
    VBoxContainer,
    HBoxContainer,
    ColorPicker,
    CenterContainer,
    EditorProperty,
    FlowContainer,
    HFlowContainer,
    VFlowContainer,

    GraphFrame,
    GraphNode,
    GridContainer,
    MarginContainer,
    PanelContainer,
    ScrollContainer,
    SplitContainer,
    HSplitContainer,
    VSplitContainer,
    SubViewportContainer,
    TabContainer,
}

impl VNodeKind {
    pub fn create_instance(&self) -> Gd<Control> {
        match self {
            VNodeKind::Control => Control::new_alloc(),
            VNodeKind::ColorRect => ColorRect::new_alloc().upcast(),
            VNodeKind::GraphEdit => GraphEdit::new_alloc().upcast(),
            VNodeKind::ItemList => ItemList::new_alloc().upcast(),
            VNodeKind::Label => Label::new_alloc().upcast(),
            VNodeKind::LineEdit => LineEdit::new_alloc().upcast(),
            VNodeKind::MenuBar => MenuBar::new_alloc().upcast(),
            VNodeKind::NinePatchRect => NinePatchRect::new_alloc().upcast(),
            VNodeKind::Panel => Panel::new_alloc().upcast(),
            VNodeKind::ReferenceRect => ReferenceRect::new_alloc().upcast(),
            VNodeKind::RichTextLabel => RichTextLabel::new_alloc().upcast(),
            VNodeKind::TabBar => TabBar::new_alloc().upcast(),
            VNodeKind::TextEdit => TextEdit::new_alloc().upcast(),
            VNodeKind::TextureRect => TextureRect::new_alloc().upcast(),
            VNodeKind::Tree => Tree::new_alloc().upcast(),
            VNodeKind::VideoStreamPlayer => VideoStreamPlayer::new_alloc().upcast(),
            VNodeKind::HSeparator => HSeparator::new_alloc().upcast(),
            VNodeKind::VSeparator => VSeparator::new_alloc().upcast(),
            VNodeKind::ProgressBar => ProgressBar::new_alloc().upcast(),
            VNodeKind::SpinBox => SpinBox::new_alloc().upcast(),
            VNodeKind::TextureProgressBar => TextureProgressBar::new_alloc().upcast(),
            VNodeKind::HSlider => HSlider::new_alloc().upcast(),
            VNodeKind::VSlider => VSlider::new_alloc().upcast(),
            VNodeKind::HScrollBar => HScrollBar::new_alloc().upcast(),
            VNodeKind::VScrollbar => VScrollBar::new_alloc().upcast(),
            VNodeKind::Button => Button::new_alloc().upcast(),
            VNodeKind::LinkButton => LinkButton::new_alloc().upcast(),
            VNodeKind::TextureButton => TextureButton::new_alloc().upcast(),
            VNodeKind::CheckBox => CheckBox::new_alloc().upcast(),
            VNodeKind::CheckBoxButton => CheckButton::new_alloc().upcast(),
            VNodeKind::ColorPickerButton => ColorPickerButton::new_alloc().upcast(),
            VNodeKind::MenuButton => MenuButton::new_alloc().upcast(),
            VNodeKind::OptionButton => OptionButton::new_alloc().upcast(),
            VNodeKind::Container => Container::new_alloc().upcast(),
            VNodeKind::AspectRatioContainer => AspectRatioContainer::new_alloc().upcast(),
            VNodeKind::BoxContainer => BoxContainer::new_alloc().upcast(),
            VNodeKind::VBoxContainer => VBoxContainer::new_alloc().upcast(),
            VNodeKind::HBoxContainer => HBoxContainer::new_alloc().upcast(),
            VNodeKind::ColorPicker => ColorPicker::new_alloc().upcast(),
            VNodeKind::CenterContainer => CenterContainer::new_alloc().upcast(),
            VNodeKind::EditorProperty => EditorProperty::new_alloc().upcast(),
            VNodeKind::FlowContainer => FlowContainer::new_alloc().upcast(),
            VNodeKind::HFlowContainer => HFlowContainer::new_alloc().upcast(),
            VNodeKind::VFlowContainer => VFlowContainer::new_alloc().upcast(),
            VNodeKind::GraphElement => GraphElement::new_alloc().upcast(),
            VNodeKind::GraphFrame => GraphFrame::new_alloc().upcast(),
            VNodeKind::GraphNode => GraphNode::new_alloc().upcast(),
            VNodeKind::GridContainer => GridContainer::new_alloc().upcast(),
            VNodeKind::MarginContainer => MarginContainer::new_alloc().upcast(),
            VNodeKind::PanelContainer => PanelContainer::new_alloc().upcast(),
            VNodeKind::ScrollContainer => ScrollContainer::new_alloc().upcast(),
            VNodeKind::SplitContainer => SplitContainer::new_alloc().upcast(),
            VNodeKind::HSplitContainer => HSplitContainer::new_alloc().upcast(),
            VNodeKind::VSplitContainer => VSplitContainer::new_alloc().upcast(),
            VNodeKind::SubViewportContainer => SubViewportContainer::new_alloc().upcast(),
            VNodeKind::TabContainer => TabContainer::new_alloc().upcast(),
        }
    }
}
